import type { AvatarProfile, AvatarCatalogEntry } from "./types";

export const AVATAR_CATALOG: AvatarCatalogEntry[] = [
  {
    profile: {
      id: "male-human-1",
      name: "Reuben",
      category: "human",
      gender: "male",
      skinTone: 0xe8b896,
      hairColor: 0x1a1a1a,
      hairStyle: "short",
      outfitColor: 0x3d3d3d,
      accentColor: 0x60a5fa,
      eyeColor: 0x3b2f2f,
      voiceId: "male-1",
      voiceName: "Reuben (English)",
      voicePitch: 1,
      voiceRate: 1,
      description: "Friendly male assistant with a warm, professional tone.",
      capabilities: {
        supportsBlink: true,
        supportsLipSync: true,
        supportsFacialExpressions: true,
        supportsHumanBreathing: true,
        supportsGestures: true,
        supportsFullBody: true,
      },
      animationProfile: {
        breathingRate: 1.1,
        blinkFrequency: 3.5,
        gazeFrequency: 0.3,
        gestureFrequency: 0.3,
        headMovementAmount: 0.04,
      },
    },
    thumbnailColor: "#3d3d3d",
    previewEmoji: "👨",
  },
  {
    profile: {
      id: "female-human-1",
      name: "Maya",
      category: "human",
      gender: "female",
      skinTone: 0xffd1c0,
      hairColor: 0x2a0a2e,
      hairStyle: "long",
      outfitColor: 0x8b3a3a,
      accentColor: 0xf472b6,
      eyeColor: 0x3d1422,
      voiceId: "female-1",
      voiceName: "Maya (English)",
      voicePitch: 1.1,
      voiceRate: 1,
      description: "Warm female assistant with a calm, empathetic voice.",
      capabilities: {
        supportsBlink: true,
        supportsLipSync: true,
        supportsFacialExpressions: true,
        supportsHumanBreathing: true,
        supportsGestures: true,
        supportsFullBody: true,
      },
      animationProfile: {
        breathingRate: 1.0,
        blinkFrequency: 3.2,
        gazeFrequency: 0.35,
        gestureFrequency: 0.25,
        headMovementAmount: 0.03,
      },
    },
    thumbnailColor: "#8b3a3a",
    previewEmoji: "👩",
  },
  {
    profile: {
      id: "futuristic-1",
      name: "Nova",
      category: "futuristic",
      gender: "female",
      skinTone: 0x9a8fb8,
      hairColor: 0x1a1a3a,
      hairStyle: "bun",
      outfitColor: 0x2d1b69,
      accentColor: 0x8b5cf6,
      eyeColor: 0x6d28d9,
      voiceId: "futuristic-1",
      voiceName: "Nova (Modern)",
      voicePitch: 1.2,
      voiceRate: 0.9,
      description: "A poised, modern-styled companion with a crisp, confident voice.",
      capabilities: {
        supportsBlink: true,
        supportsLipSync: true,
        supportsFacialExpressions: true,
        supportsHumanBreathing: true,
        supportsGestures: true,
        supportsFullBody: true,
      },
      animationProfile: {
        breathingRate: 0.9,
        blinkFrequency: 4.0,
        gazeFrequency: 0.4,
        gestureFrequency: 0.2,
        headMovementAmount: 0.05,
      },
    },
    thumbnailColor: "#2d1b69",
    previewEmoji: "🤖",
  },
  {
    profile: {
      id: "robotic-1",
      name: "Theo",
      category: "human",
      gender: "male",
      skinTone: 0x8a6a4a,
      hairColor: 0x2b2118,
      hairStyle: "short",
      outfitColor: 0x3f4a5a,
      accentColor: 0x22d3ee,
      eyeColor: 0x3b2f2f,
      voiceId: "robotic-1",
      voiceName: "Theo (Calm)",
      voicePitch: 0.85,
      voiceRate: 0.9,
      description: "A calm, analytical companion with a measured, even voice.",
      capabilities: {
        supportsBlink: true,
        supportsLipSync: true,
        supportsFacialExpressions: true,
        supportsHumanBreathing: true,
        supportsGestures: true,
        supportsFullBody: true,
      },
      animationProfile: {
        breathingRate: 0.9,
        blinkFrequency: 2.8,
        gazeFrequency: 0.3,
        gestureFrequency: 0.18,
        headMovementAmount: 0.05,
      },
    },
    thumbnailColor: "#3f4a5a",
    previewEmoji: "🧑",
  },
];

export function getAvatarProfile(id: string): AvatarProfile | undefined {
  return AVATAR_CATALOG.find((entry) => entry.profile.id === id)?.profile;
}

export function getDefaultAvatar(): AvatarProfile {
  return AVATAR_CATALOG[0].profile;
}