import type {
  ModuleContext,
  ReuCoreModule,
  ReuCoreMessage,
} from "../core/Module";

import type { SceneBlueprint } from "../blueprint/SceneBlueprintModule";

export class SVGRendererModule implements ReuCoreModule {
  readonly name = "svg-renderer";

  private context?: ModuleContext;

  initialize(context: ModuleContext) {
    this.context = context;
  }

  async onMessage(message: ReuCoreMessage) {
    if (message.type !== "SCENE_BLUEPRINT_CREATED") return;

    const blueprint = message.payload as SceneBlueprint;

    const svg = this.render(blueprint);

    await this.context?.send(
      "SVG_RENDER_COMPLETE",
      svg,
      this.name
    );
  }

  private render(scene: SceneBlueprint): string {
    const title = this.escape(scene.title);

    return `
<svg
xmlns="http://www.w3.org/2000/svg"
width="1200"
height="675"
viewBox="0 0 1200 675">

<defs>

<linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
<stop offset="0%" stop-color="#020617"/>
<stop offset="100%" stop-color="#4c1d95"/>
</linearGradient>

<radialGradient id="glow">
<stop offset="0%" stop-color="#8b5cf6"/>
<stop offset="100%" stop-color="transparent"/>
</radialGradient>

</defs>

<rect
width="1200"
height="675"
fill="url(#bg)"/>

<circle
cx="900"
cy="220"
r="250"
fill="url(#glow)"
opacity="0.55"/>

<text
x="80"
y="120"
font-size="54"
fill="white"
font-family="Arial"
font-weight="700">

${title}

</text>

<text
x="80"
y="180"
font-size="24"
fill="#cbd5e1"
font-family="Arial">

Generated by ReuCore

</text>

</svg>
`;
  }

  private escape(value: string) {
    return value
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");
  }

  healthCheck() {
    return true;
  }
}