import type { SceneBlueprint, VisualStyle } from "./types";

function detectStyle(prompt: string): VisualStyle {
  const text = prompt.toLowerCase();

  if (text.includes("hero") || text.includes("website")) return "websiteHero";
  if (text.includes("poster") || text.includes("social")) return "poster";
  if (text.includes("cinematic")) return "cinematic";
  if (text.includes("minimal")) return "minimal";
  if (text.includes("corporate") || text.includes("business")) return "corporate";

  return "futuristic";
}

function extractTitle(prompt: string) {
  const cleaned = prompt.trim();

  if (!cleaned) return "ReuNexus Visual";

  return cleaned.length > 60 ? `${cleaned.slice(0, 60)}...` : cleaned;
}

export function reasonFromPrompt(prompt: string): SceneBlueprint {
  const style = detectStyle(prompt);

  return {
    title: extractTitle(prompt),
    description: prompt,
    style,
    mood: "premium, intelligent, futuristic",
    colorPalette: ["#000000", "#7c3aed", "#a855f7", "#ffffff"],
    entities: [
      {
        id: "main-idea",
        type: "concept",
        label: prompt,
        material: "glowing digital energy",
        color: "#a855f7",
        position: { x: 0, y: 0, z: 0 },
        scale: 1,
      },
    ],
    relationships: [],
    textOverlay: {
      headline: extractTitle(prompt),
      subheadline: "Generated by ReuNexus Visual Engine",
      footer: "ReuNexus",
    },
  };
}